### ISSUE TITLE
sendtext message to group failed

### ISSUE THREAD

**Issue by Bigmacc00** [devlikeapro/whatsapp-http-api#16]
I would like to send a text message to a group with number as "xxxxxxxxxxxxxxxxxxxxxx@g.us", however it turns out "internal server error" and failed.

curl -X 'GET' \
  'http://xxxxxxx/api/sendText?phone=xxxxxxxxx%40g.us&text=test&sessionName=default' \
  -H 'accept: application/json'

**Comment by allburov** [comment]
@Bigmacc00 I've fixed the issue in `0.0.5` version!

**Comment by Bigmacc00** [comment]
I tried with the latest version, the issue seems still exist as follow. Still resulting in "internal server error" with the phone no as "xxxxxxxxxxxxxxxxxxxxxx@g.us"
![image](https://user-images.githubusercontent.com/2588786/197914874-9543b833-4f4a-40c5-bddb-b3c020654403.png)

**Comment by allburov** [comment]
Fixed and available in WAHA Core version!
